- type: docker-containers
  title: Docker Containers (pi-server)
  title-icon: mdi:docker
  hide-by-default: false
  containers:
    beszel:
      name: Beszel Hub
      description: Lightweight server monitoring platform
      url: http://pi-server.internal:8090/
      id: beszel
      icon: auto-invert sh:beszel-dark
    beszel-agent:
      name: Beszel Agent
      description: Lightweight agent for the Beszel monitoring platform
      parent: beszel
    dockge-dockge-1:
      name: Dockge
      description: A fancy, easy-to-use and reactive self-hosted docker compose.yaml stack-oriented manager
      url: http://pi-server.internal:5001
      icon: auto-invert sh:dockge-dark
    f1_api:
      name: F1_API
      description: An API for Formula 1 stats
      parent: glance
      icon: si:f1
    glances-glances-1:
      name: Glances
      description: Glances an Eye on your system
      url: http://pi-server.internal:61208
      icon: auto-invert sh:glances-dark
    homeassistant:
      name: Home Assistant
      description: Smarthome control panel
      url: http://pi-server.internal:8123
      icon: si:homeassistant
    it-tools:
      name: IT-Tools
      description: Handy tools for developers
      url: http://pi-server.internal:8080
      icon: auto-invert sh:it-tools-dark
      id: it-tools
    portracker:
      name: Portracker
      icon: auto-invert sh:portracker
    uptime-kuma:
      name: Uptime-Kuma
      description: Network service monitoring tool
      url: http://pi-server.internal:3001
      icon: auto-invert sh:uptime-kuma-dark