- type: extension
  url: http://192.168.50.2:9090/stats/benhaube
  allow-potentially-dangerous-html: true
  parameters:
    show_quartiles: true

- type: extension
  url: http://192.168.50.2:9090/graph/benhaube
  allow-potentially-dangerous-html: true
  parameters:
    background-color: "#1d2025"
    primary-color: "#151B23" 
    svg-height: 150 
    show-months: true 
    show-weekdays: true 
    font-size: 9 
    transition-hue: true 