- type: monitor
  cache: 1m
  title: Local Network Services
  title-icon: mdi:lan
  sites:
    - title: ASUS RT-BE92U
      url: https://asusrouter.internal:8443
      icon: mdi:router-wireless
      allow-insecure: true
    - title: Cloudflare Tunnel
      url: http://storage-server.internal:14333/
      icon: si:cloudflare
    - title: F1 Replay Timing
      url: http://storage-server.internal:3000
      icon: auto-invert /assets/icons/f1-replay-timing.svg
    - title: Files (storage-server)
      url: http://storage-server.internal/modules/icewhale_files/
      icon: mdi:folder-account
    - title: Glances (storage-server)
      url: http://storage-server.internal:61208/
      icon: auto-invert sh:glances-dark
    - title: Gotify
      url: https://gotify.rac3r4life.online
      icon: auto-invert /assets/icons/gotify-notification.svg
    - title: Homebox
      url: http://storage-server.internal:3100/home
      icon: auto-invert sh:homebox-dark
    - title: Immich
      url: http://storage-server.internal:2283
      icon: si:immich
    - title: Kacey (3D Printer)
      url: http://k1c-a71e.internal
      icon: auto-invert /assets/icons/creality-v1.svg
    - title: Network Documentation
      url: http://storage-server.internal:8080
      icon: mdi:file-document-multiple
    - title: Obsidian LiveSync (CouchDB)
      url: http://storage-server.internal:5984/_utils/
      icon: si:obsidian
    - title: Openprinting CUPS Server
      url: https://192.168.50.2:631/
      allow-insecure: true
      icon: mdi:printer
    - title: OpenSpeedTest
      url: http://storage-server.internal:3004/
      icon: auto-invert sh:openspeedtest-dark
    - title: Portracker
      url: http://storage-server.internal:4999
      icon: auto-invert sh:portracker
    - title: Spoolman
      url: http://storage-server.internal:7912
      icon: auto-invert sh:spoolman-dark
    - title: Technitium DNS
      url: http://debian-vm.internal:5380
      icon: auto-invert sh:technitium-dark
    - title: ttydBridge (storage-server)
      url: http://storage-server.internal:2222/
      icon: mdi:console
    - title: WireGuard Easy
      url: http://storage-server.internal:51821/
      icon: si:wireguard
    - title: yt-dlp Web UI
      url: http://storage-server.internal:3033/
      icon: auto-invert sh:youtube-dl-dark
    - title: ZimaOS NAS
      url: http://storage-server.internal
      allow-insecure: true
      icon: auto-invert sh:zimaos-dark
    - title: ZVM (storage-server)
      url: http://storage-server.internal/modules/zimaos_zvm/
      icon: auto-invert sh:qemu-dark
