- type: group
  widgets:
    - type: reddit
      title-icon: auto-invert si:f1
      style: vertical-list
      subreddit: Formula1
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true

    - type: reddit
      title-icon: mdi:newspaper
      style: vertical-list
      subreddit: F1News
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true

    - type: reddit
      title-icon: auto-invert si:f1
      style: vertical-list
      subreddit: F1TV
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true

    - type: reddit
      title-icon: mdi:wrench
      style: vertical-list
      subreddit: F1Technical
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true

    - type: reddit
      title-icon: mdi:forum
      style: vertical-list
      subreddit: F1Discussions
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true
