- type: group
  widgets:
    - type: reddit
      title-icon: mdi:android
      style: vertical-list
      subreddit: android
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true

    - type: reddit
      title-icon: mdi:fedora
      style: vertical-list
      subreddit: fedora
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true

    - type: reddit
      title-icon: mdi:firefox
      style: vertical-list
      subreddit: firefox
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true

    - type: reddit
      title-icon: auto-invert si:kde
      style: vertical-list
      subreddit: kde
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true

    - type: reddit
      title-icon: mdi:linux
      style: vertical-list
      subreddit: linux
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true

    - type: reddit
      title-icon: mdi:pi-hole
      style: vertical-list
      subreddit: pihole
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true

    - type: reddit
      title-icon: mdi:twitter
      style: vertical-list
      subreddit: whitepeopletwitter
      show-flairs: true
      limit: 10
      collapse-after: 5
      show-thumbnails: true
