- type: rss
  title: News Feed
  title-icon: mdi:racing-helmet
  style: vertical-list
  limit: 15
  collapse-after: 5
  # preserve-order: true
  cache: 12h
  feeds:
    - url: https://www.formula1.com/en/latest/all.xml
      title: Formula 1
    - url: https://www.the-race.com/rss/
      title: The Race
    - url: https://www.autosport.com/rss/f1/news/
      title: Autosport
    - url: https://www.motorsport.com/rss/f1/news/
      title: Motorsport
    - url: https://www.planetf1.com/rss
      title: PlanetF1
