- type: videos
  title: YouTube
  title-icon: mdi:youtube
  style: grid-cards
  channels:
    - UCldfgbzNILYZA4dmDt4Cd6A # Secular Talk
    - UCzIO0iX4yKW2P4NkmmKq1PA # 9to5Google
    - UCahJ9IsvXnaQiuNyWQSkrkw # Chris Norlund
    - UCyZVCV9xhrCyz4hPehvb4Wg # Internet Today
    - UCZ5cvDR2HhVUcdVoTvvQKLw # I've Had It
    - UCvhnYODy6WQ0mw_zi3V1h0g # Juan Bagnell
    - UCpa-Zb0ZcQjTCPP1Dx_1M8Q # Legal Eagle
    - UCwpHKudUkP5tNgmMdexB3ow # Mentour Pilot
    - UC7Q4rvzJDbHeBHYk5rnvZeA # The Humanist Report
    - UCxLYtICsUCWdr1YPrj5DtwA # Ordinary Things
    - UCSYCo8uRGF39qDCxF870K5Q # Owen Jones
    - UCFJxE0l3cVYU4kHzi4qVEkw # Rebecca Watson
    - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
    - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium
    - UCgyqtNWZmIxTx3b6OxTSALw # Android Authority
    - UCciQ8wFcVoIIMi-lfu8-cjQ # Anton Petrov
    - UC-9b7aDP6ZN0coj9-xFnrtw # Astrum
    - UCFpy37oq9p1MOVuJbGIcs7Q # Crumb
    - UC4dBHeQ4xfz5zBwaIcmEJfg # Dr. Caelan Conrad
    - UChIs72whgZI9w6d6FhwGGHA # Gamers Nexus
    - UCYvEb6iLPxLPZTe6NcUUUeA # j aubrey
    - UCeDKIj0G5XbultKOQnacu_w # Jose
    - UCxFWzKZa74SyAqpJyVlG5Ew # Kat Blaque
    - UCtPrkXdtCM5DACLufB9jbsA # Mr. Ballen
    - UCb-capTCx4yI3fjZrtDKKEw # Olurinatti
    - UCQSpnDG3YsFNf5-qHocF-WQ # ThioJoe
