server:
  port: 8580
  assets-path: /app/assets

# branding:
  # app-icon-url: /assets/icons/glance.png
  # hide-footer: true

theme:
  disable-picker: true
  presets:
    default-dark:
      background-color: 216 28 7
      contrast-multiplier: 1.5
      primary-color: 321 100 71
      positive-color: 136 53 51
      negative-color: 4 68 55
    default-light:
      light: true
      background-color: 240 12 95
      contrast-multiplier: 1.5
      primary-color: 321 100 71
      positive-color: 136 53 51
      negative-color: 4 68 55
  custom-css-file: /assets/user.css

auth:
  secret-key: ${secret:auth_secret}
  users:
    admin:
      password: ${secret:admin_pw_hash}
    bhaube:
      password: ${secret:bhaube_pw_hash}
    rpereira:
      password: ${secret:rpereira_pw_hash}

pages:
  - $include: pages/home.yml
  - $include: pages/network.yml
  - $include: pages/formula1.yml
